name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest

    - name: Run flake8 linter
      run: flake8 bot/
    
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Run tests
      run: pytest tests/
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}


    - name: Build Docker image
      run: docker build -t tg-bot:latest .

    - name: Установка Yandex Cloud CLI
      uses: okar1/yc-cli-install@master
      with:
        SA_KEY: ${{ secrets.YC_SA_KEY }}

    - name: Authenticate to Yandex Cloud
      run: |
        yc config set token ${{ secrets.YC_OAUTH }}
        yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
        yc config set folder-id ${{ secrets.YC_FOLDER_ID }}

    - name: Authenticate Docker to Yandex Container Registry
      run: |
        echo ${{ secrets.YC_OAUTH }} | docker login --username oauth --password-stdin cr.yandex

    - name: Tag and push Docker image to Yandex Container Registry
      run: |
        docker tag tg-bot:latest cr.yandex/<your-cloud-id>/<your-repo-name>/tg-bot:latest
        docker push cr.yandex/<your-cloud-id>/<your-repo-name>/tg-bot:latest
